### ISSUE TITLE
Spørgsmål til Lector Almedal som mistro Almedal skal spørge om

### ISSUE THREAD

**Issue by DiscoLucas** [DiscoLucas/P6-Project#13]
- Tids rum vi kan teste i?
- Om vi kan få to eller tre cases hun har lavet så vi kan se om de kan bruges?
- Kan Lektor Almdal vies os hvordan man løser kases, og om hun kan sende os en løst kase.
- Planlæg test i begyndelsen af Maj
- Tale med Lektor Almdal om hvordan testen skal forløbe.
- Bruger i en model til at forudsee/generaere rente på obligationer? Vi har kiggede på Black–Scholes model, Hull–White model og Vasicek model

**Comment by DiscoLucas** [comment]
Giver det mening at bruge et pengesystem som score? Hvis vi siger at spilleren får kommission som er sat af en procentdel af profitten på lånet. Man kunne også gøre det til en mechanic at spilleren bestemmer den procentdel, som giver dem mulighed for at tjene flere penge, men giver lånet mindre plads til falde i værdi. Kunden vil selvfølgelig også foretrække ikke at betale for meget i kommission så det er en ballancegang.

Ved heller ikke helt om rådgiverer faktisk kan tjene penge på den her måde.

**Comment by DangelTheMangel** [comment]
Hvor stor inflydelse har det på obligations markede at man invistere i en obligations eller udstider et lån. Er det sådan at en person virkelig kan skabe stor franding på markedet

**Comment by Kiliopo** [comment]
- Køre det mere som et invistering end poitsystem, så man kan få flere og færre penge.

- En enkelt privat kunde obligation vil ikke have en indflydelse på markedet.

**Comment by DangelTheMangel** [comment]
### SPØRGESMÅL TIL MØDET

Vi kunne godt bruge at blive vist de grapher de bruger til at kigge på obilgations kurser og rente

**Comment by DangelTheMangel** [comment]
Hvad vi forventer at spilleren gå igennem (procedure)

**Comment by DiscoLucas** [comment]
Vi kan åbne den igen hvis der kommer nye ting
